kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: cluster-ro-role
rules:
- apiGroups: 
  - ""
  - apps
  - extensions
  resources: 
  - deployments
  - pods
  - replicasets
  - services
  verbs:
  - get
  - list
  - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: cluster-ro-role-clusterrolebinding
subjects:
- kind: User
  name: usr-cluster
  namespace: "*"
roleRef:
  kind: ClusterRole
  name: cluster-ro-role
  apiGroup: ""
