kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: green
  name: green-role
rules:
- apiGroups: 
  - ""
  - apps
  - extensions
  resources: 
  - deployments
  - pods
  - replicasets
  - services
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: green-role-binding
  namespace: green
subjects:
- kind: User
  name: usr-green
  apiGroup: ""
roleRef:
  kind: Role
  name: green-role
  apiGroup: ""