# Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: blue
---
# MariaDB
apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-config
  namespace: blue
data:
  MYSQL_DATABASE: test_db
  MYSQL_USER: test_user
  MYSQL_PASSWORD: test_pass
  MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  namespace: blue
spec:
  replicas: 1
  selector:
    matchLabels:
      component: mariadb-label
  template:
    metadata:
      labels:
        component: mariadb-label
    spec:
      volumes:
        - name: mariadb-volume
          emptyDir: {}
      containers:
        - name: mariadb
          image: mariadb
          volumeMounts:
          - mountPath: "/var/lib/mysql"
            name: mariadb-volume
          envFrom:
          - configMapRef:
              name: mariadb-config
---
apiVersion: v1
kind: Service
metadata:  
  name: mariadb-clusterip
  namespace: blue
spec:
  selector:    
    component: mariadb-label
  type: ClusterIP
  ports:  
  - name: mariadb
    port: 3306
    targetPort: 3306
    protocol: TCP
---
# Python
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python
  namespace: blue
spec:
  replicas: 1
  selector:
    matchLabels:
      component: python-label
  template:
    metadata:
      labels:
        component: python-label
    spec:
      containers:
        - name: python
          image: mrmcshane/python:04-blue
          ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: python-lb
  namespace: blue
spec:
  type: NodePort
  ports:  
  - port: 80
    targetPort: 80
    nodePort: 30041
  selector:
    component: python-label