apiVersion: apps/v1
kind: Deployment
{{ template "first-helm-application.metadata" . }}
spec:
  revisionHistoryLimit: 2
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "first-helm-application.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "first-helm-application.labels" . | nindent 8 }}
    spec:
      containers:
        - name: python
          image: "{{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
          - containerPort: 80
