apiVersion: apps/v1
kind: Deployment
metadata:
  name: python
spec:
  replicas: 1
  selector:
    matchLabels:
      component: python-label
  template:
    metadata:
      labels:
        component: python-label
    spec:
      containers:
        - name: python
          image: mrmcshane/python
          ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: python-lb
spec:
  type: NodePort
  ports:  
  - port: 80
    targetPort: 80
    nodePort: 30003
  selector:
    component: python-label