apiVersion: apps/v1
kind: Deployment
metadata:
  name: python
spec:
  replicas: 1
  selector:
    matchLabels:
      component: python-label
  template:
    metadata:
      labels:
        component: python-label
    spec:
      containers:
        - name: python
          image: mrmcshane/python
          ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: python-lb
spec:
  type: LoadBalancer
  loadBalancerIP: 35.228.167.106
  ports:
    - port: 80
      targetPort: 80
  selector:
    component: python-label
