apiVersion: apps/v1
kind: Deployment
metadata:
  name: 03-mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      component: 03-mariadb-label
  template:
    metadata:
      labels:
        component: 03-mariadb-label
    spec:
      volumes:
        - name: 03-mariadb-volume
          persistentVolumeClaim:
            claimName: 03-mariadb-claim
      containers:
        - name: 03-mariadb
          image: mariadb
          volumeMounts:
          - mountPath: "/var/lib/mysql"
            name: 03-mariadb-volume
          env:
          # obviously don't use this in the real world
          # have some kind of secrets manager
          - name: MYSQL_RANDOM_ROOT_PASSWORD
            value: yes
          - name: MYSQL_DATABASE
            value: testdb
          - name: MYSQL_USER
            value: test_user
          - name: MYSQLPASSWORD
            value: test_pass
---
apiVersion: v1
kind: Service
metadata:
  name: 03-mariadb-node-port
spec:
  type: NodePort
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: 3306
  selector:
    component: 03-mariadb-label