apiVersion: apps/v1
kind: Deployment
metadata:
  name: python
spec:
  replicas: 1
  selector:
    matchLabels:
      component: python-label
  template:
    metadata:
      labels:
        component: python-label
    spec:
      volumes:
        - name: python-volume
          emptyDir: {}
      containers:
        - name: python
          image: andrewmcshanevaltech/python
          ports:
          - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: python-node-port
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30005
  selector:
    component: python-label