apiVersion: v1
kind: ConfigMap
metadata:
  name: special-config
  namespace: default
data:
  MYSQL_DATABASE: test_db
  MYSQL_USER: test_user
  MYSQL_PASSWORD: test_pass
  MYSQL_RANDOM_ROOT_PASSWORD: yes
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: 03-mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      component: 03-mariadb-label
  template:
    metadata:
      labels:
        component: 03-mariadb-label
    spec:
      volumes:
        - name: 03-mariadb-volume
          emptyDir: {}
      containers:
        - name: 03-mariadb
          image: mariadb
          volumeMounts:
          - mountPath: "/var/lib/mysql"
            name: 03-mariadb-volume
          envFrom:
          - configMapRef:
              name: 03-mariadb-config
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-node-port
spec:
  type: NodePort
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: 30006
  selector:
    component: 03-mariadb-label