apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: 03-mariadb-claim
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  storageClassName: slow