apiVersion: v1
kind: PersistentVolume
metadata:
  name: 03-mariadb-volume
  labels: 
    label: 03-mariadb-volume-label
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  mountOptions:
    - hard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: 03-mariadb-claim
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  storageClassName: slow
  selector: 
    matchLabels: 
      label: 03-mariadb-volume-label
 